name: mise-docs

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: mise-docs-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for lastUpdated
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: pnpm run docs:build
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for lastUpdated
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: pnpm run docs:build
      - run: mise run release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
